[
  {
    "id": "23002289",
    "etr": "ETR-NULL",
    "etrConfidence": null,
    "cluster": false,
    "comments": "We are aware of outages in this area and will provide an estimated time of restoration as soon as possible.",
    "cause": "Unable to assess due to conditions",
    "numberOut": 1,
    "custAffected": 4,
    "crewStatus": null,
    "startTime": "2023-01-12T14:09:21Z",
    "latitude": 37.77933,
    "longitude": -84.84816,
    "source": "https://kubra.io/cluster-data/300/aa3e643b-d606-4bc6-944f-a2f22f0d5879/b8e12ded-6e1e-44e5-8e15-0f4d87176ddb/public/cluster-3/0320003.json"
  }
]